###
POST http://localhost:3021/api/smartwatch HTTP/1.1
Content-Type: application/json 

{
    "name": "Casio Watch",
    "price": 300,
    "brand": "Casio",
    "color": "Black",
    "weight": 2.00,
    "battery": "15 hours"
}

###
GET http://localhost:3021/api/smartwatch/ HTTP/1.1
